name: CI/CD Pipeline #pipeline name

on:  #trigger configuration
  push:
    branches:
      - main  #trigger pipeline on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  #specify runner environment (server that runs workflows)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Log in to Amazon ECR  #AWS ECR login stage
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
 
    - name: Build Docker image  #build stage
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .

    - name: Push Docker image to ECR #push stage
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

    - name: Deploy to ECS #deploy stage
      run: |
        aws ecs update-service --cluster demo-cluster --service demo-service --force-new-deployment

    - name: Run integration tests #integration tests stage
      run: |
        curl --fail http://demo-alb-2005290699.ap-south-1.elb.amazonaws.com/health || exit 1


    - name: Rollback on failure #rollback stage
      if: failure()
      run: |
        aws ecs update-service --cluster demo cluster --service demo-service --force-new-deployment --task-definition arn:aws:ecs:ap-south-1:822311367203:task-definition/demo-ecs-task:1

